name: Install dependencies
on: 
  # push 到 schedule 分支時會觸發
  push:
    branches:
    - schedule
  # 排程每天 UTC 16:30 (台灣時間 0:30) 時觸發
  # 語法可上 crontab.guru 查詢
  schedule:
  - cron: 30 16 * * *
#channels:
#  - defaults
#  - conda-forge
#  - ctools
#dependencies:
#  - pandas
#  - bs4
#  - requests
#  - pip
#  - yapf==0.30.0
#  - flake8
